### ISSUE TITLE
Error: fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by Solxanich** [robotology/gh-action-nightly-merge#11]
Hello,

Started to receive the following error after the April 12th 2022 update to github.
```fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

The update appears to affect several others as noted here: https://stackoverflow.com/questions/71849415/cannot-add-parent-directory-to-safe-directory-on-git

Is it possible that this Actions will receive an update to fix this incompatibility with current Github? It's unusable right now.

**Comment by amansbs** [comment]
Facing the same issue

**Comment by nevinera** [comment]
(likewise)

**Comment by JavidPack** [comment]
Github actions runners are still using 2.35.1, but the docker image installs 2.35.2, where the change was implemented. I guess a temp fix could be to change the dockerfile to install a specific git version?

**Comment by gregmaghakian** [comment]
running into the same issue here

**Comment by JavidPack** [comment]
We ended up forking and applying the fix mentioned in https://github.com/actions/checkout/issues/766

The end result is this line being added: https://github.com/robotology/gh-action-nightly-merge/compare/master...tModLoader:master

Works for us.

**Comment by nevinera** [comment]
Tried @JavidPack's solution in a fork, worked for me also. Opened the PR as #13.

**Comment by traversaro** [comment]
Thanks everyone for the report and for providing a solution! We released 1.3.3 with the fix, let me know if we can close this issue.

**Comment by traversaro** [comment]
As a more general note, to be completly honest it is a bit frustrating to discover that a piece of software has users only if something is not working and users come to complain. If you are happy users of this action, feel free to Star the repo. It is an almost no-effort step, but it permits us (https://www.iit.it/, an academic institution that is maintaining  this repo) to be aware of which repositories are actually used.

**Comment by andreamussap** [comment]
> Thanks everyone for the report and for providing a solution! We released 1.3.3 with the fix, let me know if we can close this issue.

This has worked for my project. Thank you!

**Comment by foosel** [comment]
> If you are happy users of this action, feel free to Star the repo.

Just did, and also want to say, thank you very much for this action, using it a lot and it has worked great! Found this issue only after realizing what the problem was, I thought I'd introduced a merge conflict somewhere again 😅

**Comment by traversaro** [comment]
Closing the issue as @nevinera's PR seems to have worked fine, thanks a lot!
