### ISSUE TITLE
github action merge issue

### ISSUE THREAD

**Issue by dheerajappin** [robotology/gh-action-nightly-merge#17]
some days ago, i found an issue that github action merged code to iur test environment from some other branch and it is configured to auto merge from development branch, can anyone look into this

**Comment by traversaro** [comment]
Hello @dheerajappin, it is not clear what the issue is, can you be more specific and eventually provide a way to reproduce the issue? If you have any suggest fix feel free to submit a PR, thanks!

**Comment by traversaro** [comment]
@dheerajappin feel free to open a new issue if necessary.
